### ISSUE TITLE
Adding Encoding/Decoding for custom PG Types

### ISSUE THREAD

**Issue by sumo** [nikita-volkov/hasql#103]
I'm trying to define a clean interface into a set of PG tables and using functions/stored procs using custom PG types. I've defined the following:

```
CREATE TYPE ledger.posting_entry AS (
	account_id int8,
	asset_id int8,
	amount money,
	details jsonb
);

create type posted_journal as (
	journal_id int8,
	posting_ids int8[]
);

CREATE or replace function ledger.post_journal(journal varchar, entries ledger.posting_entry[]) returns posted_journal
.
.
.

```
How can I define an encoding and decoding for the custom types? I've looked through the source for the existing mappings but am not clear how to actually map to a 

`ROW(a,as,am,d) :: ledger.posting_entry` from haskell. 

I can change the interface into the function as a last resort.

**Comment by nikita-volkov** [comment]
There's no encoder for composite types, it's Postgres to blame. There are work-arounds however. For more info and the reasoning see the following issues:

- https://github.com/nikita-volkov/hasql/issues/65
- https://github.com/nikita-volkov/hasql/issues/25#issuecomment-286053459

**Comment by nikita-volkov** [comment]
> Is this do-able with Hasql 1.x?

Yes.

> I noticed a different API in #25 should I be using the dev branch instead?

`Query` was renamed to `Statement` in the recent releases of version 1.*. So what saw in the referred issues was the older API, not dev. The solutions there should absolutely be applicable.

---

Why do you cast your every parameter `cast($2 as int8[])`? The code should work without casting at all, if not then with explicit type specification at least (`$2 :: int8[]`).

There's too many things happening in your code. To determine the issue I suggest to gradually move from a simpler case step by step. Start by first ensuring that you've implemented the innermost select correctly.

**Comment by sumo** [comment]
Thanks, I simplified as suggested and it turns out that using unknown in place of a money type means that the server was unable to find the right function or cast the array correctly. Changed it to a numeric type and function resolution occurs correctly.
