### ISSUE TITLE
Hasql.Decoders.singleRow -> rowSingle

### ISSUE THREAD

**Issue by domenkozar** [nikita-volkov/hasql#107]
This is a minor annoyance I have, but all decoder functions start with `row` except for `singleRow`. Is there any reason not to make it consistent with `rowList`?

Also, `rowMaybe` is listed under `Specialized multi-row results` while it returns 1 or 0 rows.

**Comment by nikita-volkov** [comment]
The naming convention is merely about proper English and descriptiveness. The fact that `rowMaybe` and `rowList` have "row" coming first stems from the fact that they result in rows being packed in some container. There's no container `Single` and neither does "rowSingle" make sense in English.

> Also, rowMaybe is listed under "Specialized multi-row results" while it returns 1 or 0 rows.

We must have a different perception of "multi-row". I was implying varying amount.
