### ISSUE TITLE
Add error code to ConnectionError

### ISSUE THREAD

**Issue by steve-chavez** [nikita-volkov/hasql#112]
Currently, when getting a failed connection we get the error message but not the error code. Example:

```haskell
> import qualified Hasql.Pool as P
> P.acquire (1, 10, "postgres://goodUser:badPasswor@goodHost:goodPort/goodDbName") >>= (\pool -> P.use pool getPgVersion)

< Left (ConnectionError (Just "FATAL:  password authentication failed for user \"goodUser\"\nFATAL:  no pg_hba.conf entry for host \"goodHost\", user \"goodUser\", database \"goodDbName\", SSL off\n"))
```

Ideally, the `28P01` error code(as specified in https://www.postgresql.org/docs/current/errcodes-appendix.html) should be exposed in [ConnectionError](https://hackage.haskell.org/package/hasql-1.3.0.5/docs/Hasql-Connection.html#t:ConnectionError), so we can detect bad credentials without parsing the error message.

The use case comes from https://github.com/PostgREST/postgrest/issues/1285, basically we keep retrying the db connection in case of failure, but we'd like to quit when bad credentials are detected.

**Comment by nikita-volkov** [comment]
The problem is that SQLSTATE codes are only provided by "libpq" for a query result object. Since we're not yet executing any queries during the handshake, I see no way of retrieving this information from the server.

**Comment by steve-chavez** [comment]
@nikita-volkov True. That's a libpq shortcoming https://stackoverflow.com/questions/23349086/libpq-how-to-get-the-error-code-after-a-failed-pgconn-connection.

I'll close since this should be addressed in libpq first. Thank you.
