### ISSUE TITLE
Non-trivial example of using Hasql

### ISSUE THREAD

**Issue by ababo** [nikita-volkov/hasql#117]
I think we need a link to a small real-world project which demonstrates the idiomatic way of using Hasql. To show a proper data access decomposition, including transactions, error handling/logging, etc. Because adding or dividing a couple of numbers is not sufficient.

**Comment by nikita-volkov** [comment]
Unfortunately we don't have such a demo yet. I suggest searching on GitHub. There must be open-source projects serving as a good example.

**Comment by nikita-volkov** [comment]
E.g.: https://github.com/soupi/gathering/blob/master/src/Web/Gathering/Database.hs.

I got to it thru these search results: https://github.com/search?q=hasql

**Comment by ababo** [comment]
Already had a look into this project, but got an impression that it cannot serve this purpose. Looks too dirty, mixing different data libraries and using outdated Hasql version.

IMO it can make sense to maintain a small demo project as a part of Hasql.

**Comment by ababo** [comment]
I mean it can even contribute to the library design in terms of practicality.

**Comment by nikita-volkov** [comment]
I agree. I'll look thru my private projects for a candidate. I'll inform
you for feedback, once I publish.

вт, 29 окт. 2019 г., 22:45 Simon Prykhodko <notifications@github.com>:

**Comment by nikita-volkov** [comment]
Done!

https://github.com/nikita-volkov/hasql-tutorial1

**Comment by nikita-volkov** [comment]
@ababo Ping

**Comment by ababo** [comment]
@nikita-volkov Thank you, LGTM!
