### ISSUE TITLE
A "hasql" package bug: No code

### ISSUE THREAD

**Issue by torgeirsh** [nikita-volkov/hasql#119]
Found this error message in a log, and unfortunately don't have a test case to reproduce it. My understanding from the serverError function in Hasql.Private.Decoders.Result is that Postgre reported an error, but the SQLSTATE field is missing. I realise that the ServerError value can't be created without the field, but it would be useful to have more information in the error message, like the contents of the other fields (message, detail, hint).

**Comment by nikita-volkov** [comment]
Pardon. But does it not do what you ask already?
![image](https://user-images.githubusercontent.com/1560937/83283793-6bb71f00-a1e4-11ea-86be-8e293701c369.png)

**Comment by torgeirsh** [comment]
I'm not sure what you mean. I'll try to be more clear. This is the error message:

    A "hasql" package bug: No code

No ServerError is created, because "code" (SQLSTATE) is missing. Would it be possible to make this error message more helpful by including the fields message, detail, and hint?

**Comment by nikita-volkov** [comment]
Oh. Okay. I see. It's a quite unexpected behaviour of libpq. I'm wondering what's causing this. Please provide some context into this, when you find it out.

In the meantime I've replaced the crashing code with empty values. It'll be generating ServerError in such situations from now on. You'll see the changes in 1.4.3.

**Comment by torgeirsh** [comment]
Thanks, I'll report back with the improved error message if it happens again!
