### ISSUE TITLE
"Short Example" in README fails to compile

### ISSUE THREAD

**Issue by mcbahson** [nikita-volkov/hasql#120]
I copied the example from the [hasql readme](https://github.com/nikita-volkov/hasql#short-example) and attempted to build, but I received the following:

```
Main.hs:56:23: error: Operator applied to too few arguments: +
   |
56 |     select $1 :: int8 + $2 :: int8
   |
```
I'm new to Hasql, so my apologies for not seeing anything obviously wrong.

**Comment by mcbahson** [comment]
I added `{-# LANGUAGE QuasiQuotes #-}` to the top of the file and received a new error:
```
Main.hs:57:39: error:
    • Result expression is missing a typecast
    • In the quasi-quotation:
        [TH.singletonStatement|
    select $1 :: int8 + $2 :: int8
    |]
   |
57 | sumStatement = [TH.singletonStatement|
   |
```

**Comment by nikita-volkov** [comment]
You're right! It was a broken example from the beginning! We need to explicitly provide the type for each returned expression:

```haskell
[TH.singletonStatement| select ($1 :: int8 + $2 :: int8) :: int8 |]
```

**Comment by nikita-volkov** [comment]
Fixed the examples
