### ISSUE TITLE
Instances of Functor and/or Bifunctor on NullableOrNot

### ISSUE THREAD

**Issue by theobat** [nikita-volkov/hasql#131]
Is there any reason not to have a functor instance such as :

```haskell
instance Functor (NullableOrNot decoder) where
  fmap f input = case input of
    NonNullable val -> NonNullable (f <$> val)
    Nullable val -> Nullable ((fmap . fmap) f val) -- 2 fmap here to account for the maybe
```

? 

(I can make a PR if it makes sense)

**Comment by nikita-volkov** [comment]
It is not a functor. You won't be able to make it typecheck :) The `Nullable` constructor produces a value of type `NullableOrNot decoder (Maybe a)`, not `NullableOrNot decoder a`.

**Comment by theobat** [comment]
Right. Thanks for your answer.
