### ISSUE TITLE
Alternative instance?

### ISSUE THREAD

**Issue by domenkozar** [nikita-volkov/hasql#135]
I'm trying to create a decoder for a nested record which nested record as a whole can be optional as it's a `JOIN`.

Currently I have all columns nullable, but I'd prefer if rather the the column could be `Maybe Record` instead.

That could be achieved using an alternative instance or is this already supported somehow?

**Comment by nikita-volkov** [comment]
Can you provide an example statement definition?

**Comment by domenkozar** [comment]
https://gist.github.com/domenkozar/fbdb253014915464b8196c2c6d520ba3

**Comment by nikita-volkov** [comment]
What about the following change?

```haskell
houseDecoder :: HD.Row (Maybe House)
houseDecoder =  
  (\ a b -> House <$> a <*> b)
    <$> (HD.column . HD.nullable) HD.text
    <*> (HD.column . HD.nullable) HD.text
```

**Comment by domenkozar** [comment]
That way I need to maintain two decoders per each record.

**Comment by nikita-volkov** [comment]
Not sure what you mean here or what the problem is then. Can you provide an example of what you wish it was like?

**Comment by nikita-volkov** [comment]
Oh I guess you mean one version for nullable columns and one - not.
If that's the case you've made a mistake of misinterpreting similar for same and then trying to generalize over something that is by nature not general.

Your statement produces rows with two nullable columns.
It is the statement that determines that fact.
It is therefore the statement that determines how you need to decode its result rows, it is not your model.
This is why your decoders must be associated with the statement, not with your model.
This is why I recommend not trying to define reusable codecs and instead making codecs part of the statement definition.
It is not boilerplate, it is specification.
