### ISSUE TITLE
How decoding+encoding of Text (UTF-16 data) is implemented for UTF-8 client_encoding?

### ISSUE THREAD

**Issue by coderfromhere** [nikita-volkov/hasql#136]
Hi!
I've got a question regarding the implementation of the driver around handling textual data. If a PG server is set to use UTF-8 as an encoding for all textual data, how many decoding+encoding steps are made on Haskell and Postgres sides respectfully to handle queries  like this (with `Data.Text.Text` payloads which are UTF-16 under the hood)? AKA would it be better to manually `encodeUtf8` all payloads explicitly once on Haskell side to pass `bytea` payloads to the driver?
```
INSERT INTO tbl (data) VALUES (convert_to( $1 :: text, 'UTF8' ));
```
where `tbl` is defined as:
```
CREATE TABLE tbl (
    data BYTEA NOT NULL;
);
```

Postgres defines `convert_to` as `convert_to(string text, dest_encoding name) -> bytea`

**Comment by nikita-volkov** [comment]
[This](http://hackage.haskell.org/package/postgresql-binary-0.12.3.3/docs/src/PostgreSQL.Binary.Encoding.Builders.html#text_strict) is how text gets encoded on the Hasql side before being transmitted to Postgres. IOW, there's a single conversion into a UTF-8 encoding on the Hasql end. What Postgres does on its end - I don't know.

I wouldn't bother about issues like that. Sounds like a perfect example of premature optimisation and I doubt it would improve anything.

**Comment by coderfromhere** [comment]
Thanks for pointing at the implementation!  I've got a running systems that seems to be suffering from Postgres bottleneck around this kind of query and I'm just investigating how much impact each of the components may add. I guess I'll continue digging it down with profiling, I appreciate your answer nonetheless!
