### ISSUE TITLE
Could `Value` be representational?

### ISSUE THREAD

**Issue by ocharles** [nikita-volkov/hasql#137]
Currently `Hasql.Decoders.Value` takes a nominal type. This means that `Value`s cannot be coerced. This is a bit of a shame, because we could imagine having

```haskell
class HasValue a where
  value :: Value a

instance HasValue Bool where
  value = bool

newtype MyBool = MyBool Bool
  deriving newtype (HasValue)
```

I can work around this, because I can do:

```
class HasValue a where
  value :: Yoneda Value a

data Yoneda f a where
  Yoneda :: f x -> (x -> a) -> Yoneda f a
```

But this is obviously not ideal.

How do you feel about adding

```haskell
type role Value representational
```

?

**Comment by nikita-volkov** [comment]
It refuses to compile.

```
Annotation says representational but role nominal is required
```

I even tried getting down to the root of the parser hierarchy, which is

```haskell
newtype BinaryParser a =
  BinaryParser ( StateT ByteString ( Except Text ) a )
  deriving ( Functor , Applicative , Alternative , Monad , MonadPlus , MonadError Text )

type role BinaryParser representational
```

And it fails for the same reason.

**Comment by ocharles** [comment]
Hmm, I wonder what is causing it be `nominal`. Perhaps it gets all the way down to `StateT` being `nominal`? What if you explicitly write out `BinaryParser (ByteString -> Either Text (a, ByteString))`?

**Comment by nikita-volkov** [comment]
You're right! The fix will be released in 1.4.5 in minutes.

I guess I've learned something today :) Thanks!

**Comment by ocharles** [comment]
Hurrah, thanks @nikita-volkov! Now we can remove our hacky workaround :)

**Comment by nikita-volkov** [comment]
Sorry. Forgot to actually publish the package :) Now it's on Hackage.
