### ISSUE TITLE
Incorrect messaging of references to regexp capturing groups

### ISSUE THREAD

**Issue by viviag** [nikita-volkov/hasql#139]
Query in argument of `statement` function: `SELECT regexp_replace('-a',concat('^-','(b|a)'),'\1')`.
Query on Postgres side as came in `QueryError` with intended mistake (removed here, trailing zeros): `SELECT regexp_replace('-a',concat('^-','(b|a)'),'\SOH')`.

Hasql version 1.4.5.1

**Comment by nikita-volkov** [comment]
What do you believe is wrong here? I don't see

**Comment by viviag** [comment]
Parameter `'\1'` of `concat` was expected to mean reference to capturing group `(b|a)`, so was expected to be passed literally.
Instead there is '\SOH'. It results in unexpected behaviour of regexp.

It looks to me like there is no way to pass reference to capturing group, `\\1` is passed literally and is recognized as a string.
Am I wrong?

In my particular case it was possible to avoid capturing group.

**Comment by nikita-volkov** [comment]
Looks like you're confused about how escaping in Haskell works. `\\` is the way to encode a single backslash character in string literals. `\1` is how you encode a character at codepoint 1. To prove this, just see what outputting the string produces:

```
> import qualified Data.ByteString.Char8
> Data.ByteString.Char8.putStrLn "\\1"
\1
```

**Comment by viviag** [comment]
Well...
Inaccurate test. Sorry for bothering you for no reason.

repro.hs:
```
import Data.Functor.Contravariant
import Hasql.Session (Session)
import Hasql.Statement (Statement(..))
import qualified Hasql.Session as Session
import qualified Hasql.Decoders as Decoders
import qualified Hasql.Encoders as Encoders
import qualified Hasql.Connection as Connection

main :: IO ()
main = do
  Right connection <- Connection.acquire "dbname=tests user=viviag password=equimanthorn host=localhost port=5432"
  result1 <- Session.run singleSlash connection
  result2 <- Session.run doubleSlash connection
  print result1
  print result2

singleSlash :: Session Text
singleSlash = Session.statement () singleSlashStatement

doubleSlash :: Session Text
doubleSlash = Session.statement () doubleSlashStatement

singleSlashStatement :: Statement () Text
singleSlashStatement = Statement sql encoder decoder True where
  sql = "select regexp_replace('string','st(.*?)$','\1')"
  encoder = Encoders.noParams
  decoder = Decoders.singleRow (Decoders.column (Decoders.nonNullable Decoders.text))

doubleSlashStatement :: Statement () Text
doubleSlashStatement = Statement sql encoder decoder True where
  sql = "select regexp_replace('string','st(.*?)$','\\1')"
  encoder = Encoders.noParams
  decoder = Decoders.singleRow (Decoders.column (Decoders.nonNullable Decoders.text))
```

running:
```
14:45 $ stack runghc repro.hs 
Right "\SOH"
Right "ring"
```
