### ISSUE TITLE
foldl decoder is unnecessarily lazy

### ISSUE THREAD

**Issue by mitchellwrosen** [nikita-volkov/hasql#140]
Hi, I think it would be more appropriate to perform a strict left fold to avoid building up a tower of thunks that are all forced when the final accumulated result is inspected:

https://github.com/nikita-volkov/hasql/blob/7a53a069605d951f07c516553d0933b5adc48b00/library/Hasql/Private/Decoders/Result.hs#L167

Could this be changed to use `modifyIORef'` instead, or is there a particular reason to prefer the lazy variant?

**Comment by nikita-volkov** [comment]
Wow. That's a great finding! Thanks

**Comment by nikita-volkov** [comment]
Fix is released
