### ISSUE TITLE
Calling procedures

### ISSUE THREAD

**Issue by sekunho** [nikita-volkov/hasql#145]
Hello! Thanks for writing `hasql`. 

I'm looking around for postgresql libraries, found this, and I'm wondering: is it possible to call [procedures](https://www.postgresql.org/docs/14/sql-createprocedure.html)?  Something like `CALL foo(1, 2);`. I found [this comment](https://github.com/nikita-volkov/hasql/issues/30#issuecomment-84106411) which seems to suggest that it can, but I couldn't find any examples to verify this.

**Comment by nikita-volkov** [comment]
Hi! Yes. It's possible. There's nothing special about this compared to any other select. Just encode the parameters and decode the results.

**Comment by sekunho** [comment]
Thank you. I'll reopen this issue if ever I have any follow-up questions.
