### ISSUE TITLE
Does Row have to read every column? (documentation issue)

### ISSUE THREAD

**Issue by chris-martin** [nikita-volkov/hasql#153]
When defining a `Hasql.Decoders.Row`, is it mandatory for the row decoder to read every column in every row, or is row decoding allowed to halt early? For example, suppose the first column in the selected table is a `Bool` which, if `False`, means that we don't care about the rest of the row.

```haskell
column (nonNullable bool) >>= \case
    False -> pure Nothing
    True -> _ -- Decode additional columns
```

Is this sort of row decoder okay, or is there some potential problem that may arise?

**Comment by nikita-volkov** [comment]
I don't think there should be issues. Have you tried this?
