### ISSUE TITLE
Update link to PG documentation

### ISSUE THREAD

**Issue by ablearthy** [nikita-volkov/hasql#156]
In [this line](https://github.com/nikita-volkov/hasql/blob/master/library/Hasql/Private/Encoders.hs#L287) there is a link https://www.postgresql.org/docs/10/static/protocol-overview.html#protocol-format-codes.
However, since `id`s in PG documentation are written in UPPERCASE, the link doesn't lead to the right section. 

Should the link be updated to https://www.postgresql.org/docs/10/static/protocol-overview.html#PROTOCOL-FORMAT-CODES?

**Comment by nikita-volkov** [comment]
Thanks. Could you do a PR?
