### ISSUE TITLE
(Optionally) remove transitive dependencies on Template Haskell

### ISSUE THREAD

**Issue by wolfgangwalther** [nikita-volkov/hasql#163]
I am trying to cross-compile PostgREST to different architectures / OS. The biggest challenge I am facing is Template Haskell, which is notoriously hard to deal with when cross-compiling. Only build-time dependencies are relevant, because running tests when cross-compiling.. is equally hard anyway.

AFAICT, `hasql` currently depends on Template Haskell twice:
- Once through `contravariants-extra` in `hasql-transactions`:
  https://github.com/nikita-volkov/hasql-transaction/blob/2a9a710bd6230cb0abae84f14f852ab14fc3fa85/library/Hasql/Transaction/Private/Statements.hs#L41-L43
- And then by using `network-ip` in various packages (`hasql`, `hasql-implicits`, `postgresql-binary`, ... more?), which depends on `data-dword`, which is one big piece of Template Haskell. This seems to be related to encoders and decoders for postgres' `inet` type only.

The usage of `contrazip2` could trivially be replaced with `(fst >$< ...) <> (snd >$< ...)`.

Removing `network-ip` is unlikely to happen, I guess. But maybe we could add cabal flags to each package using it, to be able to disable this dependency and the related encoders/decoders? That should have no impact on other code, right? We are not using `inet` in PostgREST anyway.

I have not tried the above, yet, but would you consider accepting PRs to do the above and thus make `hasql` more friendly for cross-compiling?

**Comment by nikita-volkov** [comment]
What are the issues that you're facing with template-haskell?

Regarding removing the dependency on contravariant -extras, sure, I'll accept the PR. 

Regarding network-ip we can consider moving to a different package to represent the types. I've actually been thinking about it for other reasons anyway.

**Comment by nikita-volkov** [comment]
I must admit I've learned something today thanks to your thorough answer :)

The hasql-transaction update should get autoreleased once [the pipeline](https://github.com/nikita-volkov/hasql-transaction/actions/runs/9551914094) succeeds.


> > Regarding network-ip we can consider moving to a different package to represent the types. I've actually been thinking about it for other reasons anyway.

> How would you split that? One package per type in a monorepo setup? Or something else?

I've meant that I've been considering moving to a different package to represent those types. "network-ip" hasn't been updated since 2019. ["ip"](https://hackage.haskell.org/package/ip) seems like a viable alternative. What do you think?

**Comment by nikita-volkov** [comment]
> > The hasql-transaction update should get autoreleased once [the pipeline](https://github.com/nikita-volkov/hasql-transaction/actions/runs/9551914094) succeeds.
> 
> Seems like the pipeline is broken because of some... other dependency on template-haskell and not high enough bounds there? Funny, kind of :D

Yeah. We have the centric packages depending on template-haskell:

- https://hackage.haskell.org/package/aeson
- https://hackage.haskell.org/package/bytestring
- https://hackage.haskell.org/package/uuid-types
- https://hackage.haskell.org/package/text

Mostly to provide the instances of `Lift`.

It's likely that we've started something here based on some false assumptions.

**Comment by nikita-volkov** [comment]
Check out the Lift instances on [`Value`](https://hackage.haskell.org/package/aeson-2.2.3.0/docs/src/Data.Aeson.Types.Internal.html#line-535), [`UUID`](https://hackage.haskell.org/package/uuid-types-1.0.6/docs/src/Data.UUID.Types.Internal.html#line-577) and [`ByteString`](https://hackage.haskell.org/package/bytestring-0.12.1.0/docs/src/Data.ByteString.Internal.Type.html#line-397).

**Comment by nikita-volkov** [comment]
So do we still need to fix anything here?

**Comment by nikita-volkov** [comment]
Okay. The "hasql-transaction" update is now released. Gotta make a decision on the `inet` data-type. Does the issue with the "ip" package still stand?

**Comment by nikita-volkov** [comment]
Actually I've just come in to suggest that as well :)

**Comment by nikita-volkov** [comment]
Sure! Please do

**Comment by nikita-volkov** [comment]
The ecosystem is updated. Thanks for your contribution!
