### ISSUE TITLE
Split the "Mapping" typeclass into it's "From" and "To" counterparts?

### ISSUE THREAD

**Issue by 0x777** [nikita-volkov/hasql#17]
Currently, for any type to be an instance of the `Mapping` typeclass, you'll need to define both `renderValue` and `parseResult`. However, sometimes, I would only want a one way conversion (either to render them to binary, or read them from binary). 

If say the `Mapping` typeclass is split into `FromSql` and `ToSql` (or whatever appropriate), like how [aeson](http://hackage.haskell.org/package/aeson-0.8.0.2/docs/Data-Aeson.html#t:FromJSON) does it, it provides more flexibility in using the library.

**Comment by arkhamist** [comment]
> I'm talking about custom instances of `Mapping` here because all the same arguments apply against the proposed split classes. But there's also an extra one: I have yet to see a type which can only convert one way.

Well, it is not about types which can only be converted one way. Lets say, I've a value of type `T` that has to be inserted into the db, I'll define the `ToSQL` mapping for `T`. But, I probably would never want to read it back as `T`, but say use postgres's `json_agg` and read it is as a `Text` or as an `Aeson's` `Value` which means that I would never have to define the `FromSQL` mapping for type `T`.

**Comment by nikita-volkov** [comment]
I'm sorry, but this doesn't clear your case one bit. One type getting a trip of several conversions seems all more like a code smell to me.
