### ISSUE TITLE
Explicit rollback mechanism

### ISSUE THREAD

**Issue by jtdaugherty** [nikita-volkov/hasql#27]
I'm using Hasql in an application that needs a test suite.  As part of that test suite, I want to test database code to check that it works properly.  In doing this, the pattern I need to use is to run each test in a transaction and then roll it back. The only wan I can see to do this is to put a `fail` at the end of the `Tx` sequence for a given test to force a rollback. However, another thing I need is to return values from these tests -- such as `Bool` values indicating whether the expected comparisons succeeded.  But if I use `fail`, I can't get any such return values.

Would it be possible to provide an explicit rollback mechanism that combines these behaviors?  Say,
```
rollback :: a -> Tx c s a
```
where `rollback` triggers a rollback and returns `a` immediately.

**Comment by jtdaugherty** [comment]
It occurs to me that this would probably also need to sidestep any automatic retrying that happens in `Tx`, and that if so, maybe it'd need a better name to indicate this - such as `abort`.

**Comment by nikita-volkov** [comment]
Please refer to [the `Just False` case of `TxWriteMode`](http://hackage.haskell.org/package/hasql-0.7.2/docs/Hasql.html#t:TxWriteMode).

**Comment by jtdaugherty** [comment]
Ah, I think I remember reading that a while back and I totally forgot that it existed. Thanks!
