### ISSUE TITLE
Sqlite support

### ISSUE THREAD

**Issue by rickeyski** [nikita-volkov/hasql#29]
Hi,
I wanted to know if there are plans for a sqlite backend to hasql?

If not, I would be interested in creating a backend. To do that, how much should I base off of the Postgresql backend?

Thanks

**Comment by nikita-volkov** [comment]
I have no plans of implementing another backend. However you can expect my full cooperation if you decide to do this. 

Concerning the Postgres backend, it should serve as a fine conceptual reference, but I wouldn't expect many similarities, since it's highly specialized to Postgres.
