### ISSUE TITLE
Need a way to abort a transaction without retrying

### ISSUE THREAD

**Issue by jtdaugherty** [nikita-volkov/hasql#33]
If I use `fail` inside a `Tx` action, a transaction retry still occurs.  This is not what I want in some cases. Is there a way I can indicate that I want to abort the transaction without attempting a retry?

**Comment by jtdaugherty** [comment]
For example, one approach would be to add a constructor to `SessionError` such as `UserError Text`, and then add an action
```
abortTransaction :: Text -> Tx c s a
```
which causes the error message to be propagated to the result of calling `session` so it can be handled along with other kinds of errors.

**Comment by nikita-volkov** [comment]
You can simply use `EitherT` or `MaybeT` (in case there's no need for specific error messages) inside the transaction.

**Comment by jtdaugherty** [comment]
Can you provide an example?

**Comment by jtdaugherty** [comment]
It's also unclear to me whether any of the constuctors of the `SessionError` type are intended to be used for user-defined error conditions; the documentation implies they aren't, which is why I proposed adding another one.

**Comment by nikita-volkov** [comment]
You're correct. Custom failures are meant to be used by means of composition with other monads, e.g. the aforementioned `EitherT`.

> Can you provide an example?

Sure.
```haskell
aTxWithACustomFailure :: Tx c s (Either CustomError Int)
aTxWithACustomFailure = 
  tx txMode $ runEitherT $ do
    -- Perform an early termination,
    -- while passing a custom error:
    throwError CustomError
    -- This will never be executed:
    lift $ singleEx [stmt| SELECT 1 |]
```

**Comment by jtdaugherty** [comment]
Thanks! This worked for me, but this approach also means that essentially all of my uses of `Tx` have to be changed to return `Either CustomError a` if I want to be able to compose them (and only handle errors in one place).  That, combined with having to put `lift` everywhere, makes this pretty unpleasant.  Although I appreciate that it gives me the most control and lets me use my own type for errors, I don't think it will be worth the pain considering that I don't need to express multiple error conditions; I just want to abort with a message.

So I would still very much appreciate an easy way to abort a transaction with a text message.  Would you be willing to provide that?

**Comment by nikita-volkov** [comment]
The API is composable, which implies that it is extendable. You just have to look at it under another angle.

There's nothing stopping you from specialising on a bigger scale and propagating your errors up to the session monad. E.g.,

```haskell


import qualified Hasql
import qualified Hasql.Backend
import Control.Monad.Trans.Either
import Control.Monad.Trans.Control
import Data.Text (Text)


type Error = 
  Text


type Session c m = 
  EitherT Error (Hasql.Session c m)

session :: Functor m => 
           Hasql.Pool c -> Session c m a -> m (Either (Either Error (Hasql.SessionError c)) a)
session pool session =
  fmap (either (Left . Right) (either (Left . Left) Right)) $
  Hasql.session pool $
  runEitherT session


type Tx c s =
  EitherT Error (Hasql.Tx c s)

tx :: (Hasql.Backend.CxTx c, MonadBaseControl IO m) => 
      Hasql.TxMode -> (forall s. Tx c s r) -> Session c m r
tx mode tx =
  EitherT $ Hasql.tx mode $ runEitherT tx


```

**Comment by jtdaugherty** [comment]
Considering that I'd probably want to write this for most apps that use the library, it strikes me as something that would great either in `hasql` itself or in an extras package.  Would you be willing to add it?

**Comment by nikita-volkov** [comment]
Off the top of my head there are at least four reasons why I wouldn't be willing to add it into the "hasql" API:

1. It doesn't have anything to do with the problem area of abstracting over database APIs. Instead it only relates to the logic of a specific application, which, the way I see it, should be of its own concern.

2. It is a special case. I for one can't imagine requiring such functionality ever. The fact that you're the first to request this feature adds to that argument as well.

3. It will burden the API. The user error type will have to be abstract instead of `Text`, thus requiring yet another type parameter in both `Tx` and `Session`, which already don't seem as light as I rather want them to be.

4. As the code, which I've previously posted, proves, it is trivial to implement in your app or in your library.

**Comment by jtdaugherty** [comment]
On (1), I'm surprised at this argument, because connection pooling also fits into this category.  Connection pooling is relevant to database usage, but whether one does pooling and how it is done is also up to the application.  I view error-handling as more fundamental than connection pooling, so by this argument I think better error-handling facilities would be more useful in hasql than pooling.

On (2), I asked about adding this to the library because I don't want to write the code you posted for every application that uses this library, and I'd need to, because it provides the features I need.  But if I have to write it every time I use the library, I think that's enough evidence that including it would be useful.

On (3), I totally agree!  This is the main reason I would not want to have this included.

My objection to this approach mostly comes down to the fact that I think the above example code is going to be unwieldy to write and maintain, unpleasant to repeat, and difficult for others to understand.  Those are the concerns I'm dealing with on my end, and as much as it might be a good technical solution, I have to keep those other factors in mind.  That leaves me with two options: find another way to write it, or just hide it away in the library.

Thanks for taking the time to think about this.

**Comment by nikita-volkov** [comment]
> On (1), I'm surprised at this argument, because connection pooling also fits into this category. Connection pooling is relevant to database usage, but whether one does pooling and how it is done is also up to the application. I view error-handling as more fundamental than connection pooling, so by this argument I think better error-handling facilities would be more useful in hasql than pooling.

It's a debatable subject, however I lean to agree. I've actually considered extracting the direct access to connections and possibly isolating that API from the pool. I just haven't found a neat way to do it yet.

> On (2), I asked about adding this to the library because I don't want to write the code you posted for every application that uses this library, and I'd need to, because it provides the features I need. But if I have to write it every time I use the library, I think that's enough evidence that including it would be useful.

> My objection to this approach mostly comes down to the fact that I think the above example code is going to be unwieldy to write and maintain, unpleasant to repeat, and difficult for others to understand. Those are the concerns I'm dealing with on my end, and as much as it might be a good technical solution, I have to keep those other factors in mind. That leaves me with two options: find another way to write it, or just hide it away in the library.

It is a good argument for making a library. If you don't want maintenance obligations or don't have finite ideas about its purpose yet, just don't release it. I for one have tons of private Haskell libraries, which I use in my private end-projects, and I find it a very viable approach.

As a bottomline, I want you to understand that minimalism and isolation of concerns are my primary objectives. I'd rather see Hasql as an ecosystem of packages each dealing with its own isolated set of problems, with user being able to grab only those that he needs for his purposes. You need custom errors, I don't. Instead of providing them and forcing the users, which don't need them, to disable them, I vote for providing them in an extension library instead. However I'm not going to maintain that library, since I don't need it.

Thanks for your suggestions.

**Comment by jtdaugherty** [comment]
> As a bottomline, I want you to understand that minimalism and isolation of concerns are my primary objectives. I'd rather see Hasql as an ecosystem of packages each dealing with its own isolated set of problems, with user being able to grab only those that he needs for his purposes. You need custom errors, I don't. Instead of providing them and forcing the users, which don't need them, to disable them, I vote for providing them in an extension library instead. However I'm not going to maintain that library, since I don't need it.

It helps to understand your objectives; thanks for making them explicit.  As a user of the library, there are ways in which those concerns of minimalism and isolation of concerns really help, and I strive for the same things in many of the things I build.

My concerns, as a user of the library, mostly revolve around 1) not creating my own forks or extra libraries and 2) getting as much from the library as I can without having to write boilerplate.  I definitely appreciate that you don't have a use for the feature I've requested here, and I've said the same thing to users of my own libraries: "I don't need it, but please feel free to make your own extension."  Of course that is often not what someone wants to hear; perhaps they don't have time to do that, or to maintain it.

But I've also tried to make the case that the things I want probably deserve a home here in an effort to make your library more appealing to me and to other people who I think are likely to run into the same issues.  To me that is the balance one has to strike in writing and maintaining a library: pushing users to use it in the way you envisioned, versus integrating their feedback to make it usable in ways you didn't intend but nonetheless round out the library to make it more useful to others.  I personally lean much more toward the latter end of that spectrum with my own libraries, i.e., think critically about suggestions and reject what doesn't work, but ultimately try to listen deeply to what users are saying will make their lives better and find a way to give them what they are asking for that fits with how I want the library to work.
