### ISSUE TITLE
semicolon detection catches innocent statements

### ISSUE THREAD

**Issue by mikeplus64** [nikita-volkov/hasql#36]
For instance, function/trigger definitions such as those found here: http://www.postgresql.org/docs/9.2/static/plpgsql-trigger.html

**Comment by begriffs** [comment]
:+1: This just happened to me. Is there a workaround?

**Comment by nikita-volkov** [comment]
I'm currently working on a major revision of the whole ecosystem. If you need a fix for the existing version, I can merge a PR.
