### ISSUE TITLE
[Question] How to substitute a table name in a QuasiQuoted query?

### ISSUE THREAD

**Issue by donatello** [nikita-volkov/hasql#37]
It does not seem to be possible to pass the name of a table in a quasiquoted query using substituted params like:

```haskell
[H.stmt| INSERT INTO ? (name, age) VALUES (?, ?) |] tName kName vValue]
```

This generates a db error:

```
pg_1       | ERROR:  syntax error at or near "$1" at character 13
pg_1       | STATEMENT:  INSERT INTO $1 (name, age) VALUES ($2, $3)
```

Is there any other way to achieve this? I want to be able to write a function that can take the table name as a function argument and send queries for that table. I have asked in detail on stackoverflow.com here with more sample code and more error info - http://stackoverflow.com/questions/32309098/how-to-pass-table-name-as-a-variable-in-quasiquoted-hasql-query-code

**Comment by nikita-volkov** [comment]
Please see https://github.com/nikita-volkov/hasql/issues/2
