### ISSUE TITLE
provide upgrade path from 0.7 to 0.14

### ISSUE THREAD

**Issue by ibotty** [nikita-volkov/hasql#40]
In particular I have the following questions.
- How do transactions work?
- Is it right, that one has to be explicit when constructing a Hasql.Query.Query? Is there no type inference anymore?

Thanks for your efforts.

**Comment by nikita-volkov** [comment]
I'm in the midst of doing a lot of documentation for the new release and the infrastructure will get massive updates quite soon. Expect all that to be covered within two weeks.

**Comment by nikita-volkov** [comment]
> How do transactions work?

There will be an extension library which will reproduce the older `Tx` abstraction very closely. It's implemented already, but needs some polishing.

> Is it right, that one has to be explicit when constructing a Hasql.Query.Query? Is there no type inference anymore?

Type inference revolves around the `Default` typeclass now. You can use `def` for the unambiguous cases.

**Comment by ibotty** [comment]
I see, so it's not yet published. I was wondering what happened. I will restrain from updating for now then. Thanks for your answer.

**Comment by nikita-volkov** [comment]
Yeah. Probably it's best to wait a bit.

I had to publish the library without that much docs because I was giving a talk about it on the past weekend.

**Comment by TravisWhitaker** [comment]
@ibotty, if you're interested in migrating an existing application, when constructing a new `Query`, I've found it helpful to define some QQ like:

```haskell
qq = QuasiQuoter (\a -> [|fromString a|]) (_) (_) (_)
```

Since one's queries are likely to be within a QQ anyway.

**Comment by nikita-volkov** [comment]
@TravisWhitaker
Mine are not actually, I've just been using the standard multiline string syntax and am pretty happy so far. E.g.,

```haskell
selectOfJSONByKeyAndJSONPointer :: Query (Key, JSONPointer) (Maybe JSON)
selectOfJSONByKeyAndJSONPointer =
  statement sql encoder decoder True
  where
    sql =
      "select json #> $3 \
      \from document \
      \where source_type = $1 and source_id = $2"
    encoder =
      contrazip2 Encoders.key (Encoders.value Encoders.textArrayFromJSONPointer)
    decoder =
      fmap join $
      Decoders.maybeRow $
      Decoders.nullableValue Decoders.jsonb
```
