### ISSUE TITLE
Encoder for "unknown" type in Hasql 0.15

### ISSUE THREAD

**Issue by begriffs** [nikita-volkov/hasql#44]
I notice that Hasql.PTI exposes

```haskell
unknown = mkPTI 705  Nothing
```

But Hasql.Encoders does not provide a function to construct this kind of Value, along the lines of

```haskell
unknown :: Value Int64
unknown =
  Value (Value.unsafePTI PTI.unknown (const Encoder.unknown))
```

In fact I don't see an `unknown` encoder in PostgreSQL.Binary.Encoder. Would it difficult to add the ability to create these values? I'd like to pass a ByteString and have postgresql do its best to coerce it.

**Comment by nikita-volkov** [comment]
I suppose you imply:

```haskell
unknown :: Value ByteString
```

Sure!

**Comment by nikita-volkov** [comment]
Released
