### ISSUE TITLE
Why does UTCTime transcode to timezonetz when UTCTime inherently has no timezone?

### ISSUE THREAD

**Issue by kanadskiy** [nikita-volkov/hasql#45]
If `UTCTime` represents a UTC time, why does it encode/decode with `timestamptz`? Seems like `UTCTime` should actually transcode with `timestamp` since it is the UTC time...

Consequently, `timestamptz` should convert into a type with time zone information like `ZonedTime`.

**Comment by nikita-volkov** [comment]
From [documentation](http://hackage.haskell.org/package/hasql-0.19.6/docs/Hasql-Decoders.html#v:timestamptz):

> Postgres does not store the timezone information of TIMESTAMPTZ. Instead it stores a UTC value and performs silent conversions to the currently set timezone, when dealt with in the text format. However this library bypasses the silent conversions and communicates with Postgres using the UTC values directly.

It is a quite controversial decision of the Postgres designers, I agree. However a driver library needs to conform.

**Comment by kanadskiy** [comment]
OK, but I'm confused as to the difference with `LocalTime`. Is there a reason why `timestamp` decodes to `LocalTime` and not also to `UTCTime`? Seems like they are both representations of the date/time with no time zone information.

**Comment by nikita-volkov** [comment]
`timestamp` does not imply the timezone information at all, that is including "UTC+0". Of course, you can use it with an implication that it represents the UTC time, but that can only be by your custom convention. Postgres provides no such implications or guarantees. Hence if you're looking to store a UTC value, `timestamptz` is the only proper option.

You might be surprised, but in the beginning of this project, the dates were set up exactly oppositely, but then I had [this discussion](https://github.com/nikita-volkov/hasql-postgres/issues/1).

**Comment by kanadskiy** [comment]
I think you summed it up perfectly, this makes sense to me now the difference between the two. Thank you, I think I learned something today!
