### ISSUE TITLE
Seems like Hasql array decoders don't like empty arrays

### ISSUE THREAD

**Issue by chris-kahn** [nikita-volkov/hasql#46]
Postgres treats an empty array as an array with 0 dimensions, so trying to parse a empty 1-dimensional array fails with the error `ResultError (RowError 0 (ValueError "A missing dimension length"))`.

Is there a recommended way to handle empty arrays?

**Comment by nikita-volkov** [comment]
What have you tried?

**Comment by kanadskiy** [comment]
I started by simplifying the example on Hackage:

    textarray :: Value [Text]
    textarray = array (arrayDimension replicateM (arrayValue text))

**Comment by nikita-volkov** [comment]
Okay. Thanks. I'll look into that soon.
