### ISSUE TITLE
Support ByteString.Lazy

### ISSUE THREAD

**Issue by ruslantalpa** [nikita-volkov/hasql#51]
In PostgREST we get the main response body as `Data.ByteString.Char8` from postgres/hasql only to convert it to Data.ByteString.Lazy and send it to the user

It would be cool if here 
https://github.com/nikita-volkov/hasql/blob/master/library/Hasql/Decoders.hs#L346
we could also have bytea_lazy

It seems to be possible since you already have that here
https://github.com/nikita-volkov/postgresql-binary/blob/master/library/PostgreSQL/Binary/Decoder.hs#L244

I am far from understanding all these types and the format of the data sent by postgresql over the wire but am i right in saying that if we implement this then we would basically stream raw bytes sent by postgresql to the http client?
Any other places we should touch to get postgrest to just `forward/stream` the data from the database?

Thank you

**Comment by nikita-volkov** [comment]
Unfortunately this is a limitation of "libpq", the low-level C driver, that it sends blobs over completely without streaming. So it simply doesn't make sense to provide a codec for lazy datastructures. I've actually been meaning to remove the one from the "postgresql-binary" library.

**Comment by ruslantalpa** [comment]
Thank you, makes sense (bummer though)
