### ISSUE TITLE
Question about creating query with named parameters

### ISSUE THREAD

**Issue by rikvdkleij** [nikita-volkov/hasql#57]
How do I create query with named parameters? In haddock I only see way to created query with positional parameters.

**Comment by nikita-volkov** [comment]
It's not possible.

What for? Why? How do you expect to associate with codecs in such a case?

**Comment by rikvdkleij** [comment]
Because code is more readable and less chance for mistakes.

By putting name/codec pairs in a map?

**Comment by nikita-volkov** [comment]
I see. Well, it's not supported.

I also don't believe it would have made the code any more readable or reduced the chance for mistakes. If anything it would have made it more verbose and noisy, that is besides introducing a performance overhead.

**Comment by rikvdkleij** [comment]
Okay.

One last question for now :-) (I'm using hasql for the first time)

In example code of older version of hasql I see use of quasi quotes to create statements. Why is that removed from hasql?

**Comment by nikita-volkov** [comment]
There was a lot of conceptual evolution in the library. The quasi-quotes are by far not the only thing that went away. One of the reasons was that quasi-quotes-based API failed to support the use-cases with dynamic generation of statements. E.g., the "postgrest" project requires that.

Nowadays the library provides a foundation for all kinds of use-cases. Any higher-level APIs, including the reproduction of the older quasi-quotes behaviour, can be implemented as extensions in separate libraries.

**Comment by rikvdkleij** [comment]
Thanks for your reply!
