### ISSUE TITLE
Please provide an example of composite value decoding

### ISSUE THREAD

**Issue by kaol** [nikita-volkov/hasql#58]
I'm having difficulty using ```Composite```. Could you please provide an example of how to decode something basic like ```select (1,'a');``` in the documentation?

**Comment by nikita-volkov** [comment]
Should be pretty straight-forward:

```haskell
decoder :: Result (Int64, Char)
decoder =
  singleRow (value (composite ((,) <$> compositeValue int8 <*> compositeValue char)))
```

**Comment by kaol** [comment]
Unfortunately I couldn't get it to work. Anything I tried seemed to give me a `ResultError (RowError 0 (ValueError "End of input"))`. If there's a complete, small example program somewhere that uses `composite` I would love to see it.

In the end, I ended up doing it like this, just to get it done somehow.

```sql
create type integerpair as ("1" integer, "2" integer);
select (val)."1", (val)."2" from (select cast((1,2) as integerpair) as val) as x;
```

**Comment by nikita-volkov** [comment]
Actually it appears that you've discovered a bug. I'm fixing it right now and post back on the results.

**Comment by nikita-volkov** [comment]
Fixed in 0.19.15.2

**Comment by nikita-volkov** [comment]
Whoever needs an example, it's in tests now:
https://github.com/nikita-volkov/hasql/blob/08564ab360b80b473dbd4999ce7259f4b421ba1e/tasty/Main.hs#L27-L35

**Comment by karls** [comment]
Hi Nikita,

Sorry to resurrect a closed issue.

I'm also having some problems with Composite. While the test case you've written works, I'm having trouble getting it to work for "larger" examples. In my own codebase, I'm doing a big join that returns a list of 4-tuples of domain entities (plain Haskell records), e.g `[(Entity1, Entity2, Entity3, Entity4)]`. I have Composite decoders for all the entities and I'm doing basically what you're doing in the Composite test.

I have written a failing test for an example that (I think) should work https://github.com/karls/hasql/commit/9362f35ec7e5a37c45302ab01625f60a78163000.

In my application, the big join query outputs rows of 4 columns, each column being the tuple representation of the corresponding table/entity. Essentially, a copy-paste from psql console for the big join query (using fictional entities) would look something like this:
```
      entity1      |       entity2      |     entity3     |      entity4
-------------------+--------------------+-----------------+------------------
 ("hi", 3, true)   |  ("name", "karl")  |   ("age", 28)   |  ("alive", true)
```

The test I've written fails with `ResultError (RowError 0 (ValueError "End of input"))`, but in my application the error seems to be
 `RowError 0 (ValueError "Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream")`.

Any ideas would be greatly appreciated.

**Comment by nikita-volkov** [comment]
@karls  Can you please PR with your test?
