### ISSUE TITLE
Dynamic Query

### ISSUE THREAD

**Issue by WongKamFu** [nikita-volkov/hasql#60]
How do I do dynamic query with Hasql, like INSERT a table with unknown column / variable number of columns?
Thanks a lot

**Comment by nikita-volkov** [comment]
If you want to use a parametric query with binary codecs, then just construct `Query` dynamically and make it unpreparable. Otherwise you can just sidestep `Query` and simply generate the final SQL, running it using `Session.sql`.

**Comment by WongKamFu** [comment]
Got it, how did I miss this.
Thanks a lot

**Comment by nikita-volkov** [comment]
From now on we have a library that helps to construct dynamic statements: http://hackage.haskell.org/package/hasql-dynamic-statements
