### ISSUE TITLE
Better debugging: Show queries

### ISSUE THREAD

**Issue by agrafix** [nikita-volkov/hasql#62]
I've had some bad queries, but it took some time to figure out what exactly did go wrong. It would have been very helpful to see the query (after placeholder-replacement) along with the error messages.

**Comment by nikita-volkov** [comment]
I agree. I've suffered from that myself a couple of times. It would be nice to have the error messages extended with the query. I'll look into it some time later.

> (after placeholder-replacement)

There's no placeholder replacement in Hasql. The query gets transferred to the db with no modifications. So, I'm afraid, it'll only be the template that will be shown.

**Comment by agrafix** [comment]
Template is good for a first step, would be awesome if one could hit the database to also see the "full query", but I guess it doesn't really exist and postgres does not support this atm.

**Comment by chris-kahn** [comment]
Have you tried turning on query logging in Postgres? In my dev environments I'm setting `log_statement = 'all'`, and postgres will log the query template as well as the replacements it used for each value.

**Comment by chris-kahn** [comment]
It would be nice to at least get extra information into the decoder errors, which column failed, what was the value that couldn't be parsed. And, this one happens to me a lot... `UnexpectedNull`... which column was null?

**Comment by domenkozar** [comment]
Could `Query a b` provide a show instance? I think then it would be easier to implement logging on top of `Hasql.Session.query`, etc.

**Comment by nikita-volkov** [comment]
> Could Query a b provide a show instance?

Please post that as a dedicated issue and describe how you want the Show instance to behave.

**Comment by nikita-volkov** [comment]
Solved in Hasql 1.3
