### ISSUE TITLE
Unable to encode array of composites

### ISSUE THREAD

**Issue by bgamari** [nikita-volkov/hasql#65]
The encoders supplied in `Hasql.Encoders` are not expressive enough to represent an array of composite values. Specifically, `arrayValue` expects a `Value`, which isn't a semigroup.

**Comment by nikita-volkov** [comment]
There's intentionally no encoders for composite types, because Postgres doesn't provide enough support for them (on the OID) level.

**Comment by bgamari** [comment]
Nikita Volkov <notifications@github.com> writes:

> There's intentionally no encoders for composite types, because Postgres doesn't provide enough support for them (on the OID) level.
>
What precisely is missing? Yes, you need to know the OID of the
composite you are trying to construct, but it nevertheless should be
possible to represent them.

**Comment by nikita-volkov** [comment]
There is no predefined OID for a composite type

**Comment by tekul** [comment]
Is there some way of working around this? I have a table which has an array of text, integer pairs and I'm not sure how to update or insert to that with Hasql. Would I have to build the explicit SQL for the entire command, including the array content?

**Comment by nikita-volkov** [comment]
>Would I have to build the explicit SQL for the entire command, including the array content?

That's an option you always have.

As for the alternative, I recommend exploring something in the spirit of [a solution to multiple values, based on unzipping of arrays](https://github.com/nikita-volkov/hasql/issues/25#issuecomment-286053459). (Please, post back if you find a solution).

BTW, some form of support for composite encoding is likely to come in the next major release.

**Comment by tekul** [comment]
Thanks a lot for your super fast response! With the help of that link I managed to get it to work, though I'm pushing my boundaries somewhat, and there may be a better way :). Since my composite type only has two fields it's not overly complex. As suggested I split it into two separate arrays of type `text` and `int2` and then recombine them with a cast in the SQL.

The relevant part of my schema is:

```
CREATE TYPE dict_entry AS (word text, index smallint);

CREATE TABLE story
    ( story_id text PRIMARY KEY
    , title text NOT NULL
    , img_url text NOT NULL
    , level smallint NOT NULL CHECK (level >= 0 AND level < 10)
    , curriculum text NOT NULL CHECK (length(curriculum) > 0)
    , tags text[] NOT NULL
    , content text NOT NULL CHECK (length(content) > 0)
    , words dict_entry[] NOT NULL
    , created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
```
and my corresponding Hasql code is
```
evText :: E.Params Text
evText = E.value E.text

insertStory :: Query Story ()
insertStory = Q.statement sql storyEncoder D.unit True
  where
    sql = "INSERT INTO story (story_id, title, img_url, level, curriculum, tags, content, words) \
                 \VALUES ($1, $2, $3, $4, $5, $6, $7, (array(select word::dict_entry from unnest ($8, $9) as word)))"

storyEncoder :: E.Params Story
storyEncoder =
    contramap (fromJust . storyId) evText <>
    contramap title evText <>
    contramap img evText <>
    contramap (fromIntegral . storyLevel) (E.value E.int4) <>
    contramap (head . tags) evText <>
    contramap (tail . tags) (array E.text) <>
    contramap content evText <>
    contramap (map word . words) (array E.text) <>
    contramap (map (fromIntegral . index) . words) (array E.int2)
  where
    array v = E.value (E.array (E.arrayDimension foldl' (E.arrayValue v)))
    storyId = id :: Story -> Maybe Text
    storyLevel = level :: Story -> Int

```
The Haskell data types can be found [here](https://github.com/ThreeMinuteLearning/my3ml/blob/3e0f2c4db4f8b8674536ce39838941fa54a5c155/api/Api/Types.hs#L20).

**Comment by nikita-volkov** [comment]
Yes. Seems like a good solution. Thanks for posting back!
