### ISSUE TITLE
Error from variable substitution in 'SET' statement

### ISSUE THREAD

**Issue by mschristiansen** [nikita-volkov/hasql#66]
I've posted this issue on stackoverflow [stackoverflow](http://stackoverflow.com/questions/41940819/hasql-error-from-variable-substitution-in-set-statement/41940959#41940959).

Summary below if other people run into same issue.

```
import qualified Hasql.Encoders as E
import qualified Hasql.Decoders as D

setOrganization :: Query Int64 ()
setOrganization = statement sql (E.value E.int8) D.unit False
  where
    sql = "set my_session.organization_id = $1"
```

This results in:
```
ResultError (ServerError "42601" "syntax error at or near \"$1\"" Nothing Nothing)
```

**Comment by nikita-volkov** [comment]
So that we don't breed multiple threads of discussion, let's continue it on the original StackOverflow thread.
