### ISSUE TITLE
Decoders/encoders for Network Addres Types 

### ISSUE THREAD

**Issue by rikvdkleij** [nikita-volkov/hasql#68]
I can not find encoders and decoders for network address types as `inet` and `cidr`. Is there specific reason they are missing?

**Comment by nikita-volkov** [comment]
Simply no research has been commenced on the according binary codecs. You can take it on if you want. The according PRs will be merged.

**Comment by rikvdkleij** [comment]
I will give it a try..

I just cloned project and used `stack init` to create `stack.yaml`. Stack choose resolver `nightly-2017-02-03` (so GHC 8.0.2) . Build and run the tests. Some of the tests are failing:
```
  Unknown:                                             FAIL
    expected: Right True
     but got: Left (SessionError (ResultError (ServerError "3F000" "no schema has been selected to create in" Nothing Nothing)))
  Enum:                                                FAIL
    expected: Right "ok"
     but got: Left (SessionError (ResultError (ServerError "3F000" "no schema has been selected to create in" Nothing Nothing)))
  The same prepared statement used on different types: OK
  Affected rows counting:                              FAIL
    expected: Right 100
     but got: Left (SessionError (ResultError (ServerError "3F000" "no schema has been selected to create in" Nothing Nothing)))
  Result of an auto-incremented column:                FAIL
    expected: Right (1,2)
     but got: Left (SessionError (ResultError (ServerError "3F000" "no schema has been selected to create in" Nothing Nothing)))
```
Do I have to create local database?

**Comment by nikita-volkov** [comment]
No. It seems like you're missing the default "postgres" schema. The tests assume that you have it.

**Comment by rikvdkleij** [comment]
I have default postgres schema. Also, not all tests are failing.

**Comment by nikita-volkov** [comment]
This is definitely due to your local Postgres configuration, the tests run fine on the default Travis configuration. I think the following should help with your issue: http://dba.stackexchange.com/q/106057/52225.

Also please notice that all Hasql codecs are actually implemented in a separate project: https://github.com/nikita-volkov/postgresql-binary. Hasql merely provides wrappers.

**Comment by rikvdkleij** [comment]
Yes, it was my local Postgres configuration.

The roundtrip test is working for the `inet` datatype. I will sent PR if it's completely ready.

**Comment by nikita-volkov** [comment]
> Do not depend on other package, just use tuple of 4 Word8's for IP4 and Word8 for netmask;

Since there's no standard package for those types, it's best to have the neutral option. Hence is my vote for this.

**Comment by rikvdkleij** [comment]
> Since there's no standard package for those types, it's best to have the neutral option. Hence is my vote for this.

I agree.

Another question. I'm almost there :smile: 
For IPv6 I have so serialize `Word16`s to list. `ByteString.pack` can only serialize `Word8`. So I looked around on hackage and I found package `binary`. Do you agree with using this library?

**Comment by rikvdkleij** [comment]
Hmm, when I use `LazyByteString` the tests fail...

**Comment by rikvdkleij** [comment]
Nevermind, I will try another solution, maybe with 'cereal' package.

**Comment by nikita-volkov** [comment]
No. There's no need for either of those packages. All the tools you need are in "bytestring".

Please look at the implementations of other codecs in [https://github.com/nikita-volkov/postgresql-binary](postgresql-binary).

**Comment by rikvdkleij** [comment]
I have it working for IP4 with and without netmask. Tests are passing.

Point is, for IP6 I need function to go from '[Word16]' to 'ByteString'.

**Comment by nikita-volkov** [comment]
Can be [this](http://hackage.haskell.org/package/bytestring-0.10.8.1/docs/Data-ByteString-Builder.html#v:word32BE) or [this](http://hackage.haskell.org/package/bytestring-0.10.8.1/docs/Data-ByteString-Builder.html#v:word16LE). You'll have to detect, which endianness they use in Postgres, with tests.

**Comment by rikvdkleij** [comment]
Thanks for your tip.

I'm making progress again, hopefully I see all tests passing soon.

**Comment by rikvdkleij** [comment]
It's done 😄
