### ISSUE TITLE
Profunctor instances for Query?

### ISSUE THREAD

**Issue by arianvp** [nikita-volkov/hasql#74]
So I see `Query` is an instance of all the lovely `Arrow*` typelcasses and also `Profunctor`.  

But as far as I know. `Strong` and `Arrow` are basically the same. Would there be any objection to adding
`Data.Profunctor.Choice` and `Data.Profunctor.Strong` instances for `Query`? I could write up a PR

**Comment by nikita-volkov** [comment]
Sure. I must inform you though that there's a work on a major rewrite happening on [the "dev" branch](https://github.com/nikita-volkov/hasql/tree/dev). One noticeable difference will be that Query (renamed to Statement) will lose the Arrow instances. Profunctor will stay though.

If you want your changes to make it to the next major release I suggest to apply them to the "dev" branch.

**Comment by arianvp** [comment]
Why would you drop the arrow instances though if I may ask?

**Comment by nikita-volkov** [comment]
They achieve nothing that can't be done with the Session Monad. Monads are simpler and I'd rather reduce the alternatives of doing the same thing. There are other reasons as well.

**Comment by arianvp** [comment]
Alright. then perhaps we should not add `Profunctor, Strong, Choice` as that is basically adding `Arrows` back with different typeclass names :)   I'll play with the new release once it's out and see if I have a need for them.

**Comment by nikita-volkov** [comment]
No problem. BTW, Profunctor won't go anywhere, it doesn't require the Arrow instance. The "dev" branch already has an instance of Profunctor.

**Comment by nikita-volkov** [comment]
The new release is in a testing phase. You can play with it. It's 0.20. 0.19 has now become 1.

**Comment by arianvp** [comment]
:+1:

**Comment by arianvp** [comment]
What exactly is the point of the `1` release?   shouldnt'  `1` be the one with all the breaking changes?

**Comment by nikita-volkov** [comment]
1 is the stable release. The breaking changes are yet in the experimental state, hence the "0.x" version space.
