### ISSUE TITLE
Control.Monad.Trans.Either from package either has been dropped

### ISSUE THREAD

**Issue by mgmeier** [nikita-volkov/hasql#83]
When building with the latest version of `either`, this happens:
`Could not find module ‘Control.Monad.Trans.Either'`

From `either`'s changelog for version 4.5:

> Deprecate Control.Monad.Trans.Either in favor of Control.Monad.Trans.Except

After being deprecated for some time, the module has now been dropped in version 5.

I know that the constraint on `either` in the .cabal file says `< 5`, so this is not an actual bug report... however, it would be nice to be able to build with the most up-to-date dependencies. Do you see `hasql` switching to any of the replacements proposed in the changelog?

> Use Control.Monad.Trans.Except from transformers and/or transformers-compat instead.

**Comment by nikita-volkov** [comment]
It's fixed in 1.1.1
