### ISSUE TITLE
Expose Connection from Session

### ISSUE THREAD

**Issue by rightfold** [nikita-volkov/hasql#85]
I think it would be useful to have the connection available in a session, in order to use libpq functions (with `withLibPQConnection`) from a session. Currently this can be worked around by passing the connection to the function that returns the session computation, but since `Session` is a reader anyway (internally), it might as well expose it. This wouldn't change anything resource safety-wise, because there is no linearity constraint on `Session.run` that would prevent the connection from being used in the session anyway (especially with the `MonadIO` instance).

```haskell
connection :: Session Connection
```

**Comment by carlosdagos** [comment]
@rightfold almost 5 years later but see #152 👍🏼

**Comment by nikita-volkov** [comment]
Sorry for neglecting this issue. Session has a MonadReader instance, which provides access to the Connection by means of `ask`.
