### ISSUE TITLE
Add support for referencing result fields by names

### ISSUE THREAD

**Issue by nikita-volkov** [nikita-volkov/hasql#96]
The issue was posted as a comment in another thread:

https://github.com/nikita-volkov/hasql/issues/75#issuecomment-415542579

**Comment by nikita-volkov** [comment]
I'm feel strongly against this. I see no benefit over the current approach based on the order of results and this will greatly complicate the API.

Concerning the argument for being able to decode the results of `select * from people` statement. Nothing stops you from decoding such results in current Hasql. The order of fields in such result is guaranteed to be the same as the order of columns. The requirement for you to change the order of your codecs may only arise when you change the schema of your DB. But then changing schema clearly requires you to review and test your statements regardless of whether they select with `*` or not.

**Comment by nikita-volkov** [comment]
> With a positional system, if those two columns are swapped, money might start flowing in the wrong direction. If that query was decoded via column name instead of position, the system would not change.

If you can imagine a programmer introducing a bug by swapping the results, why can't you imagine that he can use wrong field names in decoders just as well? It is just all the same mistake done on different levels and named references is just as much susceptible to it.

---

It looks like you're missing the point that in Hasql codecs are supposed to be an integral part of the statement specification. I.e., the SQL template is supposed to be defined together with codecs. Hence introducing a change to any part of that specification implies that the other parts are supposed to be changed in accordance.

The approach that "hasql-generic" library introduces makes this abstraction leak. I.e., with it the codecs are defined separately from the SQL template. I believe it is wrong. And it feels like your suggestion is coming from you experiencing the abstraction leak of "hasql-generic". Trust me, if you try using Hasql the suggested way (with explicit specifications instead of typeclasses), you'll feel that in reality there is no problem.


> I wonder if this is something that could be avoided by offering column-name-decoding via an opt-in library

Nah. It would require Hasql to provide all the hooks for such a library, which would imply extending the API and basically bundling such a library in.

**Comment by leemhenson** [comment]
:D

I sense a philosophical divide that cannot be crossed. 

> It would require Hasql to provide all the hooks for such a library, which would imply extending the API and basically bundling such a library in.

Ok, that's basically the crux of this issue ends this discussion! Thanks for sharing a great library anyway. 🍻 I'm sure I'll find something in Servant or whatever to distract me from positional decoders. 😅
