### ISSUE TITLE
tested, getting started example in README

### ISSUE THREAD

**Issue by domenkozar** [nikita-volkov/hasql#98]
Hey @nikita-volkov 

first of all, hats off for this library, I'm really enjoying its design for simplicity.

I really missed in the begining how to put the puzzles together, for a simple example to get started.  Would you mind if I make a PR to add something like https://github.com/well-typed/pretty-sop#example (which would be also a literate haskell and part of test-suites).

**Comment by nikita-volkov** [comment]
Thanks! You're more than welcome to do so!
