### ISSUE TITLE
Relax the revision on `hasql-1.3.0.3` to allow it to build with `text-builder-0.5.4.3`

### ISSUE THREAD

**Issue by DanBurton** [nikita-volkov/hasql#99]
When starting the build of this week's Stackage LTS snapshot (lts-12.9, still in progress), I had to use revision 0 of `hasql-1.3.0.3`, since [the latest revision](http://hackage.haskell.org/package/hasql-1.3.0.3/revisions/) currently disallows building with `text-builder-0.5.*`.

text-builder-0.5.4.3 is out of bounds for:
- hasql-1.3.0.3 (>=0.6.1.2 && < 0.7). Nikita Volkov <nikita.y.volkov@mail.ru> @nikita-volkov. @nikita-volkov. Used by: library

It would be preferable if the latest revision supported building with both acceptable versions of `text-builder-0.5.*` (for LTS), as well as `text-builder-0.6.*` (for nightly).

**Comment by nikita-volkov** [comment]
Done!
